version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm@8.15.0
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile
      
  build:
    commands:
      - echo "Building all packages..."
      - export DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder"
      - pnpm build
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'packages/*/dist/**/*'
    - 'packages/*/build/**/*'
    - 'packages/*/.next/**/*'
    - '!packages/*/.next/cache/**/*'
  base-directory: .

cache:
  paths:
    - 'node_modules/**/*'
    - 'packages/*/node_modules/**/*'
